### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by Greg-J** [bacco-bacco/MCRGB#2]
What are the chances we could get this for Fabric 1.19.2?

**Comment by bacco-bacco** [comment]
No promises yet, but I'll look into it! :)

**Comment by sayore** [comment]
pleaseeeeeee

**Comment by bacco-bacco** [comment]
I'll have to rework some code for 1.19.2 compatibility.
I'm planning to start it in a week, so expect a 1.19.2 release by the end of the month! 😉

**Comment by sayore** [comment]
I love you, you are the best 🎉

**Comment by bacco-bacco** [comment]
MCRGB v0.2.3 is now available for Minecraft 1.19.2! 🎉

Happy New Year! 😀
