### ISSUE TITLE
Mod versions seem to not be updated

### ISSUE THREAD

**Issue by haykam821** [bacco-bacco/MCRGB#3]
The versions on Modrinth named [`MCRGB 0.2.3-1.20.2`](https://modrinth.com/mod/mcrgb/version/0.2.3-1.20.2) and [`MCRGB 0.2.4-1.20.4`](https://modrinth.com/mod/mcrgb/version/OLs0AQuB) seem to both have a version number of `0.2.2-1.20.2`, which is already used by an existing version. I assume the versions should be unique to match the names on Modrinth.

As a side note, using a `+` instead of `-` for the Minecraft version in the version is recommended to avoid issues with sorting versions.

**Comment by bacco-bacco** [comment]
Thanks for bringing this to my attention. This will be corrected in future versions.
