### ISSUE TITLE
The game takes much longer than usual to load due to the mod.

### ISSUE THREAD

**Issue by ChemaMC** [bacco-bacco/MCRGB#7]

**Comment by LaineZ** [comment]
Same issue. Stucks on this
``[00:13:17] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.``

**Comment by bacco-bacco** [comment]
@LaineZ I can't replicate the issue, using the same mod list. Could you provide a full log file?

**Comment by bacco-bacco** [comment]
Closing this issue as unable to replicate.
